"""Test whether the optimum can be regenerated by a Siamese-style local rule.

The useful part of a Siamese construction is that the next number is placed by
a fixed short move, with a fixed correction move when that cell is blocked.
This module reads the reconstructed optimum backward as the value order
1 -> 2 -> ... -> 270 and measures whether that order compresses to such a rule.
"""

from __future__ import annotations

import json
from collections import Counter

from .hexgrid import Cell, HexGrid, add


def hex_distance(a: Cell, b: Cell) -> int:
    """Hex-graph distance between two axial coordinates."""
    dq = a[0] - b[0]
    dr = a[1] - b[1]
    return max(abs(dq), abs(dr), abs(dq + dr))


def _inverse(values: dict[Cell, int]) -> dict[int, Cell]:
    return {v: c for c, v in values.items()}


def _candidate_vectors(max_radius: int) -> list[Cell]:
    return [
        (q, r)
        for q in range(-max_radius, max_radius + 1)
        for r in range(-max_radius, max_radius + 1)
        if (q, r) != (0, 0) and max(abs(q), abs(r), abs(q + r)) <= max_radius
    ]


def _best_fixed_rule(values: dict[Cell, int], grid: HexGrid,
                     max_step_radius: int) -> dict:
    """Check the best short primary/fallback move pair against the optimum order."""
    inv = _inverse(values)
    filled = set(grid.filled)
    vectors = _candidate_vectors(max_step_radius)
    best = {
        "matches": -1,
        "prefix_matches": -1,
        "primary": None,
        "fallback": None,
        "first_failure_at": None,
    }
    for primary in vectors:
        for fallback in vectors:
            used: set[Cell] = set()
            matches = 0
            prefix_matches = 0
            prefix_alive = True
            first_failure_at = None
            for v in range(1, 270):
                used.add(inv[v])
                cand = add(inv[v], primary)
                if cand not in filled or cand in used:
                    cand = add(inv[v], fallback)
                ok = cand == inv[v + 1]
                if ok:
                    matches += 1
                    if prefix_alive:
                        prefix_matches += 1
                elif prefix_alive:
                    first_failure_at = v
                    prefix_alive = False
            if (matches, prefix_matches) > (best["matches"], best["prefix_matches"]):
                best = {
                    "matches": matches,
                    "prefix_matches": prefix_matches,
                    "primary": primary,
                    "fallback": fallback,
                    "first_failure_at": first_failure_at,
                }
    return best


def analyze_siamese(values: dict[Cell, int], grid: HexGrid,
                    max_step_radius: int = 3) -> dict:
    """Summarize whether the optimum's value order admits a Siamese-style rule."""
    inv = _inverse(values)
    deltas = []
    distances = []
    for v in range(1, 270):
        a = inv[v]
        b = inv[v + 1]
        deltas.append((b[0] - a[0], b[1] - a[1]))
        distances.append(hex_distance(a, b))

    delta_counts = Counter(deltas)
    distance_counts = Counter(distances)
    best_rule = _best_fixed_rule(values, grid, max_step_radius)
    local_transitions = sum(1 for d in distances if d <= max_step_radius)

    return {
        "model": "fixed short move plus fixed fallback, no wraparound",
        "max_step_radius": max_step_radius,
        "n_transitions": len(deltas),
        "distinct_deltas": len(delta_counts),
        "singleton_deltas": sum(1 for n in delta_counts.values() if n == 1),
        "top_deltas": [
            {"delta": list(delta), "count": count}
            for delta, count in delta_counts.most_common(20)
        ],
        "distance_histogram": [
            {"distance": dist, "count": count}
            for dist, count in sorted(distance_counts.items())
        ],
        "max_distance": max(distances),
        "mean_distance": sum(distances) / len(distances),
        "local_transition_count": local_transitions,
        "local_transition_ratio": local_transitions / len(distances),
        "best_fixed_rule": {
            **best_rule,
            "primary": list(best_rule["primary"]),
            "fallback": list(best_rule["fallback"]),
            "match_ratio": best_rule["matches"] / len(deltas),
        },
        "verdict": (
            "Failure: the optimum's value order is not regenerated by a "
            "Siamese-style polynomial-time local rule. Consecutive values use "
            "120 different displacement vectors, and the best short "
            "primary/fallback move pair matches only 6 of 269 transitions."
        ),
        "classical_chinese_reconstruction": [
            "今按其圖，數雖成六觚之均，非一行添六可循而得也。",
            "以一數次第求其所之，或遠或近，步法凡百二十變。",
            "設常步一、塞則更步一以試之，二百六十九遷中僅中六遷。",
            "故此圖宜謂以對位相補而搜得其均，不宜謂暹羅一路可成。",
        ],
        "source_correspondence": [
            {
                "original": "置外周添六",
                "modern_check": "Reading 添六 as a fixed value-placement move fails.",
                "classical_chinese": "非一行添六可循而得也",
            },
            {
                "original": "虛一則二百七十數",
                "modern_check": "The center remains void; only the 270 filled cells are analyzed.",
                "classical_chinese": "虛其中一，以二百七十數布之",
            },
            {
                "original": "通加洛書數六倍",
                "modern_check": "The count 270=6×45 and the complementary-pair structure remain valid.",
                "classical_chinese": "六觚之均，由對位相補而成",
            },
        ],
    }


def write_siamese_json(analysis: dict, path: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(analysis, f, ensure_ascii=False, indent=2)


def write_siamese_markdown(analysis: dict, path: str) -> None:
    lines = [
        "# Siamese-Style Local Rule Reverse Engineering",
        "",
        "## Verdict",
        "",
        analysis["verdict"],
        "",
        "This check rereads the optimum in the value order `1 -> 2 -> ... -> 270`",
        "and asks whether the next cell is determined, as in Siamese magic-square",
        "constructions, by a short primary move plus a short fallback move.",
        "",
        "## Measurements",
        "",
        f"- Transitions: {analysis['n_transitions']}",
        f"- Distinct displacement vectors: {analysis['distinct_deltas']}",
        f"- Singleton displacement vectors: {analysis['singleton_deltas']}",
        f"- Maximum hex distance: {analysis['max_distance']}",
        f"- Mean hex distance: {analysis['mean_distance']:.3f}",
        f"- Local transitions within radius {analysis['max_step_radius']}: "
        f"{analysis['local_transition_count']} / {analysis['n_transitions']} "
        f"({analysis['local_transition_ratio']:.3%})",
        "",
        "## Best Short Siamese Candidate",
        "",
    ]
    r = analysis["best_fixed_rule"]
    lines.extend([
        f"- Primary move: {r['primary']}",
        f"- Fallback move: {r['fallback']}",
        f"- Matched transitions: {r['matches']} / {analysis['n_transitions']} "
        f"({r['match_ratio']:.3%})",
        f"- First failure: {r['first_failure_at']} -> {r['first_failure_at'] + 1}",
        f"- Prefix transitions matched from the start: {r['prefix_matches']}",
        "",
        "## Classical Chinese Restatement",
        "",
    ])
    lines.extend(f"- {s}" for s in analysis["classical_chinese_reconstruction"])
    lines.extend(["", "## Source Correspondence", "", "| Source phrase | Modern check | Classical Chinese restatement |", "|---|---|---|"])
    for row in analysis["source_correspondence"]:
        lines.append(f"| {row['original']} | {row['modern_check']} | {row['classical_chinese']} |")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
